config/routes.rb
Rails.application.routes.draw do
	scope "(:locale)", :locale => /en|de/ do
		root  'pages#index'
		match 'est',          to: 'pages#est',          via: 'post'
		match 'dienstnehmer', to: 'pages#dienstnehmer', via: 'post'
		match 'dienstgeber',  to: 'pages#dienstgeber',  via: 'post'
		match 'favicon',      to: 'pages#favicon',      via: 'get'

		match '/stats',       to: 'stats#index',        via: 'get'
		match '/stats',       to: 'stats#data',         via: 'post'

	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container" style="margin-bottom: 20px;">
	  <nav>
	    <ul>
	      <li><a href="https://www.ownyourdata.eu" onmousedown="$('#stats_target').val('oyd_footer');$('#stats_form').submit();">OwnYourData.eu</a> © 2020</li>
	      <li> <a href="https://www.ownyourdata.eu/de/impressum/" style="margin: 0 10 0 0px;" onmousedown="$('#stats_target').val('imprint');$('#stats_form').submit();">Impressum</a></li>
          <li><a href="https://www.ownyourdata.eu/de/datenschutz/" style="margin: 0 10 0 0px;" onmousedown="$('#stats_target').val('privacy');$('#stats_form').submit();">Datenschutz</a></li>
	    </ul>
	  </nav>
	</div>
</footer>

app/views/layouts/_header.html.erb
<div style="background-color: #F2F3F9;">
  <div class="container">
    <div class="row">
      <div class="col-md-12" style="min-height: 60px; margin-top: 20px;">
        <div style="white-space: nowrap;">
          <div style="display: inline-block;"><%= image_tag 'oyd.png', style: "height: 60px; margin: -20px -5px -10px -10px; vertical-align: text-bottom;" %></div>
          <div style="display: inline-block;">
            <h1 class="visible-xs visible-sm hidden-md hiden-lg" style="text-align: left; margin-bottom: 10px; font-size: x-large; padding-right: 110px;"><div class="title-link">Brutto-Netto-Rechner</div></h1>
            <h1 class="hidden-xs hidden-sm visible-md visible-lg" style="text-align: left; margin-bottom: 10px; font-size: x-large;"><div class="title-link">Brutto-Netto-Rechner</div></h1>
          </div>
          
          <a href="https://www.ownyourdata.eu/" style="color: #42B58C; text-decoration: none; white-space: nowrap;" class="oyd-link" onmousedown="$('#stats_target').val('oyd_header');$('#stats_form').submit();">
            <span style="text-decoration: underline;">
              ownyourdata.eu</span> 
            <i class="fa fa-long-arrow-up" aria-hidden="true" style="-webkit-transform:rotate(30deg); -moz-transform:rotate(30deg); -ms-transform:rotate(30deg); -o-transform:rotate(30deg); transform:rotate(30deg);"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','<%= ENV["GOOGLE_TOKEN"] %>');</script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
  </head>

  <body>
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<%= ENV["GOOGLE_TOKEN"] %>" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  	<%= render 'layouts/header' %>
<%= form_with url: stats_path, id: "stats_form" do |form| %>
    <%= form.hidden_field :stats_target, id: "stats_target" %>
<% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>